# https://focused-minsky-b08e8a.netlify.com/

# Notes
#  - Doesn't know how to handle .js content files, but that could
#    probably be written. In the meantime, jsxtreme-markdown might get us to where we need

backend:
  name: github
  repo: jseppi/netlifycms-experiment

media_folder: "src/pages/static"
public_folder: "/static"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Individual Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "src/pages/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "products"
    label: "Product Page"
    folder: "src/pages/products"
    create: true
    extension: js
    format: yaml-frontmatter
    frontmatter_delimiter:
      - "/*---"
      - "---*/"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"} # TODO: would want to make a code editor widget for this
  - name: "industries"
    label: "Industry Page"
    folder: "src/pages/industries"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Text", name: "heroText", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
