# https://focused-minsky-b08e8a.netlify.com/

backend:
  name: github
  repo: jseppi/netlifycms-experiment

media_folder: "src/pages/static"
public_folder: "/static"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Consumer Industry Page"
        name: "consumer"
        file: "src/pages/industries/consumer.js"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Text", name: "heroText", widget: "string"}
          - {label: "Featured Image", name: "featuredImage", widget: "image"}
          - {label: "Description", name: "description", widget: "markdown"}
  # - name: "industries"
  #   label: "Industry Pages"
  #   folder: "src/pages/industries"
  #   create: true
  #   # slug: "{{slug}}.js"
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Hero Text", name: "heroText", widget: "string"}
  #     - {label: "Featured Image", name: "featuredImage", widget: "image"}
  #     - {label: "Description", name: "description", widget: "markdown"}
