# https://focused-minsky-b08e8a.netlify.com/

backend:
  name: github
  repo: jseppi/netlifycms-experiment

media_folder: "src/pages/static"
public_folder: "/static"

collections:
  - name: "industries"
    label: "Industry Pages"
    folder: "src/pages/industries"
    create: false
    slug: "{{slug}}.js"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Text", name: "heroText", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
